# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lami/proto/lami.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15lami/proto/lami.proto\x12\x0flami.proto.lami\"X\n\x0fLamiObservation\x12\'\n\x03obs\x18\x01 \x01(\x0b\x32\x1a.lami.proto.lami.LamiState\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"\x19\n\tLamiState\x12\x0c\n\x04stat\x18\x01 \x01(\x0c\"\x1c\n\nLamiAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x0c\x62\x06proto3')



_LAMIOBSERVATION = DESCRIPTOR.message_types_by_name['LamiObservation']
_LAMISTATE = DESCRIPTOR.message_types_by_name['LamiState']
_LAMIACTION = DESCRIPTOR.message_types_by_name['LamiAction']
LamiObservation = _reflection.GeneratedProtocolMessageType('LamiObservation', (_message.Message,), {
  'DESCRIPTOR' : _LAMIOBSERVATION,
  '__module__' : 'lami.proto.lami_pb2'
  # @@protoc_insertion_point(class_scope:lami.proto.lami.LamiObservation)
  })
_sym_db.RegisterMessage(LamiObservation)

LamiState = _reflection.GeneratedProtocolMessageType('LamiState', (_message.Message,), {
  'DESCRIPTOR' : _LAMISTATE,
  '__module__' : 'lami.proto.lami_pb2'
  # @@protoc_insertion_point(class_scope:lami.proto.lami.LamiState)
  })
_sym_db.RegisterMessage(LamiState)

LamiAction = _reflection.GeneratedProtocolMessageType('LamiAction', (_message.Message,), {
  'DESCRIPTOR' : _LAMIACTION,
  '__module__' : 'lami.proto.lami_pb2'
  # @@protoc_insertion_point(class_scope:lami.proto.lami.LamiAction)
  })
_sym_db.RegisterMessage(LamiAction)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LAMIOBSERVATION._serialized_start=42
  _LAMIOBSERVATION._serialized_end=130
  _LAMISTATE._serialized_start=132
  _LAMISTATE._serialized_end=157
  _LAMIACTION._serialized_start=159
  _LAMIACTION._serialized_end=187
# @@protoc_insertion_point(module_scope)
