# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krl/proto/actor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15krl/proto/actor.proto\x12\x0fkrl.proto.actor\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\" \n\nServerList\x12\x12\n\nserver_ids\x18\x01 \x03(\t\",\n\x05\x41gent\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\r\"c\n\x0fGameObservation\x12%\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x16.krl.proto.actor.Agent\x12)\n\x0bobservation\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"J\n\x10GameObservations\x12\x36\n\x0cobservations\x18\x01 \x03(\x0b\x32 .krl.proto.actor.GameObservation\"Y\n\nGameAction\x12%\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x16.krl.proto.actor.Agent\x12$\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"{\n\x0bGameActions\x12,\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x1b.krl.proto.actor.GameAction\x12\x11\n\tdone_envs\x18\x02 \x03(\t\x12+\n\x0b\x64one_agents\x18\x03 \x03(\x0b\x32\x16.krl.proto.actor.Agent2\xa4\x01\n\x05\x41\x63tor\x12T\n\x0fSendObservation\x12!.krl.proto.actor.GameObservations\x1a\x1c.krl.proto.actor.GameActions\"\x00\x12\x45\n\x0cResetServers\x12\x1b.krl.proto.actor.ServerList\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_SERVERLIST = DESCRIPTOR.message_types_by_name['ServerList']
_AGENT = DESCRIPTOR.message_types_by_name['Agent']
_GAMEOBSERVATION = DESCRIPTOR.message_types_by_name['GameObservation']
_GAMEOBSERVATIONS = DESCRIPTOR.message_types_by_name['GameObservations']
_GAMEACTION = DESCRIPTOR.message_types_by_name['GameAction']
_GAMEACTIONS = DESCRIPTOR.message_types_by_name['GameActions']
ServerList = _reflection.GeneratedProtocolMessageType('ServerList', (_message.Message,), {
  'DESCRIPTOR' : _SERVERLIST,
  '__module__' : 'krl.proto.actor_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.actor.ServerList)
  })
_sym_db.RegisterMessage(ServerList)

Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), {
  'DESCRIPTOR' : _AGENT,
  '__module__' : 'krl.proto.actor_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.actor.Agent)
  })
_sym_db.RegisterMessage(Agent)

GameObservation = _reflection.GeneratedProtocolMessageType('GameObservation', (_message.Message,), {
  'DESCRIPTOR' : _GAMEOBSERVATION,
  '__module__' : 'krl.proto.actor_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.actor.GameObservation)
  })
_sym_db.RegisterMessage(GameObservation)

GameObservations = _reflection.GeneratedProtocolMessageType('GameObservations', (_message.Message,), {
  'DESCRIPTOR' : _GAMEOBSERVATIONS,
  '__module__' : 'krl.proto.actor_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.actor.GameObservations)
  })
_sym_db.RegisterMessage(GameObservations)

GameAction = _reflection.GeneratedProtocolMessageType('GameAction', (_message.Message,), {
  'DESCRIPTOR' : _GAMEACTION,
  '__module__' : 'krl.proto.actor_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.actor.GameAction)
  })
_sym_db.RegisterMessage(GameAction)

GameActions = _reflection.GeneratedProtocolMessageType('GameActions', (_message.Message,), {
  'DESCRIPTOR' : _GAMEACTIONS,
  '__module__' : 'krl.proto.actor_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.actor.GameActions)
  })
_sym_db.RegisterMessage(GameActions)

_ACTOR = DESCRIPTOR.services_by_name['Actor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERLIST._serialized_start=98
  _SERVERLIST._serialized_end=130
  _AGENT._serialized_start=132
  _AGENT._serialized_end=176
  _GAMEOBSERVATION._serialized_start=178
  _GAMEOBSERVATION._serialized_end=277
  _GAMEOBSERVATIONS._serialized_start=279
  _GAMEOBSERVATIONS._serialized_end=353
  _GAMEACTION._serialized_start=355
  _GAMEACTION._serialized_end=444
  _GAMEACTIONS._serialized_start=446
  _GAMEACTIONS._serialized_end=569
  _ACTOR._serialized_start=572
  _ACTOR._serialized_end=736
# @@protoc_insertion_point(module_scope)
