# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from krl.proto import learner_pb2 as krl_dot_proto_dot_learner__pb2


class LearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSamples = channel.unary_unary(
                '/krl.proto.learner.Learner/SendSamples',
                request_serializer=krl_dot_proto_dot_learner__pb2.Sample.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class LearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSamples(self, request, context):
        """Send Observations Of Game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSamples,
                    request_deserializer=krl_dot_proto_dot_learner__pb2.Sample.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'krl.proto.learner.Learner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Learner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/krl.proto.learner.Learner/SendSamples',
            krl_dot_proto_dot_learner__pb2.Sample.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
