# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krl/proto/learner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17krl/proto/learner.proto\x12\x11krl.proto.learner\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x06Sample\x12\x13\n\x0bpolicy_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32M\n\x07Learner\x12\x42\n\x0bSendSamples\x12\x19.krl.proto.learner.Sample\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_SAMPLE = DESCRIPTOR.message_types_by_name['Sample']
Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLE,
  '__module__' : 'krl.proto.learner_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.learner.Sample)
  })
_sym_db.RegisterMessage(Sample)

_LEARNER = DESCRIPTOR.services_by_name['Learner']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLE._serialized_start=75
  _SAMPLE._serialized_end=118
  _LEARNER._serialized_start=120
  _LEARNER._serialized_end=197
# @@protoc_insertion_point(module_scope)
