# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krl/proto/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15krl/proto/model.proto\x12\x0fkrl.proto.model\x1a\x1bgoogle/protobuf/empty.proto\")\n\x19ModelLatestVersionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"-\n\x1aModelLatestVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\r\"K\n\x0cModelVersion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x62\x61se_version\x18\x02 \x01(\r\x12\x17\n\x0frequest_version\x18\x03 \x01(\r\"\x7f\n\x10\x46\x65tchModelResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bnew_version\x18\x02 \x01(\r\x12\x37\n\x0cmodel_pramas\x18\x03 \x01(\x0b\x32\x1c.krl.proto.model.ModelParamsH\x00\x88\x01\x01\x42\x0f\n\r_model_pramas\")\n\x0bModelParams\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\x8d\x02\n\x05Model\x12\x43\n\tSendModel\x12\x1c.krl.proto.model.ModelParams\x1a\x16.google.protobuf.Empty\"\x00\x12P\n\nFetchModel\x12\x1d.krl.proto.model.ModelVersion\x1a!.krl.proto.model.FetchModelResult\"\x00\x12m\n\x10GetLatestVersion\x12*.krl.proto.model.ModelLatestVersionRequest\x1a+.krl.proto.model.ModelLatestVersionResponse\"\x00\x62\x06proto3')



_MODELLATESTVERSIONREQUEST = DESCRIPTOR.message_types_by_name['ModelLatestVersionRequest']
_MODELLATESTVERSIONRESPONSE = DESCRIPTOR.message_types_by_name['ModelLatestVersionResponse']
_MODELVERSION = DESCRIPTOR.message_types_by_name['ModelVersion']
_FETCHMODELRESULT = DESCRIPTOR.message_types_by_name['FetchModelResult']
_MODELPARAMS = DESCRIPTOR.message_types_by_name['ModelParams']
ModelLatestVersionRequest = _reflection.GeneratedProtocolMessageType('ModelLatestVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODELLATESTVERSIONREQUEST,
  '__module__' : 'krl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.model.ModelLatestVersionRequest)
  })
_sym_db.RegisterMessage(ModelLatestVersionRequest)

ModelLatestVersionResponse = _reflection.GeneratedProtocolMessageType('ModelLatestVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODELLATESTVERSIONRESPONSE,
  '__module__' : 'krl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.model.ModelLatestVersionResponse)
  })
_sym_db.RegisterMessage(ModelLatestVersionResponse)

ModelVersion = _reflection.GeneratedProtocolMessageType('ModelVersion', (_message.Message,), {
  'DESCRIPTOR' : _MODELVERSION,
  '__module__' : 'krl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.model.ModelVersion)
  })
_sym_db.RegisterMessage(ModelVersion)

FetchModelResult = _reflection.GeneratedProtocolMessageType('FetchModelResult', (_message.Message,), {
  'DESCRIPTOR' : _FETCHMODELRESULT,
  '__module__' : 'krl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.model.FetchModelResult)
  })
_sym_db.RegisterMessage(FetchModelResult)

ModelParams = _reflection.GeneratedProtocolMessageType('ModelParams', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAMS,
  '__module__' : 'krl.proto.model_pb2'
  # @@protoc_insertion_point(class_scope:krl.proto.model.ModelParams)
  })
_sym_db.RegisterMessage(ModelParams)

_MODEL = DESCRIPTOR.services_by_name['Model']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELLATESTVERSIONREQUEST._serialized_start=71
  _MODELLATESTVERSIONREQUEST._serialized_end=112
  _MODELLATESTVERSIONRESPONSE._serialized_start=114
  _MODELLATESTVERSIONRESPONSE._serialized_end=159
  _MODELVERSION._serialized_start=161
  _MODELVERSION._serialized_end=236
  _FETCHMODELRESULT._serialized_start=238
  _FETCHMODELRESULT._serialized_end=365
  _MODELPARAMS._serialized_start=367
  _MODELPARAMS._serialized_end=408
  _MODEL._serialized_start=411
  _MODEL._serialized_end=680
# @@protoc_insertion_point(module_scope)
