# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from krl.proto import model_pb2 as krl_dot_proto_dot_model__pb2


class ModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendModel = channel.unary_unary(
                '/krl.proto.model.Model/SendModel',
                request_serializer=krl_dot_proto_dot_model__pb2.ModelParams.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.FetchModel = channel.unary_unary(
                '/krl.proto.model.Model/FetchModel',
                request_serializer=krl_dot_proto_dot_model__pb2.ModelVersion.SerializeToString,
                response_deserializer=krl_dot_proto_dot_model__pb2.FetchModelResult.FromString,
                )
        self.GetLatestVersion = channel.unary_unary(
                '/krl.proto.model.Model/GetLatestVersion',
                request_serializer=krl_dot_proto_dot_model__pb2.ModelLatestVersionRequest.SerializeToString,
                response_deserializer=krl_dot_proto_dot_model__pb2.ModelLatestVersionResponse.FromString,
                )


class ModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendModel(self, request, context):
        """Send Observations Of Game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModel,
                    request_deserializer=krl_dot_proto_dot_model__pb2.ModelParams.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'FetchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchModel,
                    request_deserializer=krl_dot_proto_dot_model__pb2.ModelVersion.FromString,
                    response_serializer=krl_dot_proto_dot_model__pb2.FetchModelResult.SerializeToString,
            ),
            'GetLatestVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestVersion,
                    request_deserializer=krl_dot_proto_dot_model__pb2.ModelLatestVersionRequest.FromString,
                    response_serializer=krl_dot_proto_dot_model__pb2.ModelLatestVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'krl.proto.model.Model', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Model(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/krl.proto.model.Model/SendModel',
            krl_dot_proto_dot_model__pb2.ModelParams.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/krl.proto.model.Model/FetchModel',
            krl_dot_proto_dot_model__pb2.ModelVersion.SerializeToString,
            krl_dot_proto_dot_model__pb2.FetchModelResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLatestVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/krl.proto.model.Model/GetLatestVersion',
            krl_dot_proto_dot_model__pb2.ModelLatestVersionRequest.SerializeToString,
            krl_dot_proto_dot_model__pb2.ModelLatestVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
